FROM ruby:4.0.7-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential default-libmysqlclient-dev pkg-config libyaml-dev libvips curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails
ENV RAILS_ENV=development

EXPOSE 3000
CMD ["ruby", "bin/rails", "server", "-b", "0.0.0.0"]
