default: &default
  adapter: mysql2
  encoding: utf8mb4
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1").to_json %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USERNAME", "todo").to_json %>
  password: <%= ENV.fetch("DB_PASSWORD", "").to_json %>

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  primary:
    <<: *default
    database: todo_production
  cache:
    <<: *default
    database: todo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: todo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: todo_production_cable
    migrations_paths: db/cable_migrate
